### ISSUE TITLE
Headship Stats CSS

### ISSUE THREAD

**Issue by lindig** [johnwalley/bumps-results#20]
On macOS Safari the head ship stats don't render properly. I understand this is not a data issue. You can see in the screenshot that the data is present but not rendered legibly. The problem is related to light/dark mode - it does work in dark mode.

![Screenshot 2024-07-21 at 11 55 46](https://github.com/user-attachments/assets/39494773-bb58-44ea-b8f7-f5415f410c5b)

**Comment by johnwalley** [comment]
Good spot. Some quirk to do with mixing numbers and percentages for the background gradient colours. I've pushed a fix.

**Comment by lindig** [comment]
It works for me now. Suggest to close this.
